name: PluginManager
version: '${project.version}'
main: net.daechler.pluginmanager.PluginManager
api-version: 1.19
authors: [ Daechler ]
description: Load, unload and reload plugins without restarting your server.
commands:
  pmload:
    description: Load a plugin.
    aliases: pml
    usage: /pmload
    permission: pmload.use
  pmunload:
    description: Unload a plugin.
    aliases: pmu
    usage: /pmunload
    permission: pmunload.use
  pmreload:
    description: Reload a plugin.
    aliases: pmr
    usage: /pmreload
    permission: pmreload.use